Fixed bug causing a crash
Fixed a bug that resulted in t2t crashing with the error message:
```
Traceback (most recent call last):
  File "/srv/sw//tax2tree/dev/bin/t2t", line 5, in <module>
    pkg_resources.run_script('tax2tree==1.0-dev', 't2t')
  [...]
  File "/srv/sw/tax2tree/dev/lib/python2.7/site-packages/tax2tree-1.0_dev-py2.7.egg/t2t/nlevel.py", line 496, in name_node_score_fold
    node_to_keep = tiebreak_f(tie_nodes)
  File "/srv/sw/tax2tree/dev/lib/python2.7/site-packages/tax2tree-1.0_dev-py2.7.egg/t2t/nlevel.py", line 436, in min_tips
    scores.append(len(n.tips()))
TypeError: object of type 'generator' has no len()
```